package pdm;

import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DashboardStudent extends javax.swing.JFrame {
    
    private DefaultTableModel modelMahasiswa;

    public void loadTableData() {
        while (modelMahasiswa.getRowCount() > 0) {
            modelMahasiswa.removeRow(0);
        }
        try {
            //isi tabel
            for (Mahasiswa mhs : Database.getInstance().getListMahasiswa()) {
                modelMahasiswa.addRow(new Object[]{mhs.getNim(), mhs.getNama(), mhs.getJk(), mhs.getProdi(), mhs.getKelas()});

            }
        } catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(this, "Gagal memuat data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void filterTableData() {
        String cariMahasiswa = txCariData.getText();
        DefaultTableModel tabelModelMahasiswa = new DefaultTableModel();

        tabelModelMahasiswa.addColumn("NIM");
        tabelModelMahasiswa.addColumn("Nama Mahasiswa");
        tabelModelMahasiswa.addColumn("Jenis Kelamin");
        tabelModelMahasiswa.addColumn("Program Studi");
        tabelModelMahasiswa.addColumn("Kelas");

        try {
            String sql = "SELECT * FROM mhs WHERE concat(nim, nama, jk, prodi, kelas) LIKE '%" + cariMahasiswa + "%'";
            PreparedStatement p = Config.getConnection().prepareStatement(sql);
            ResultSet r = p.executeQuery();
            while (r.next()) {
                tabelModelMahasiswa.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),});
            }
            tableMahasiswa.setModel(tabelModelMahasiswa);
            loadTableData();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Cari data mahasiswa error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Creates new form DashboardStudent
     */
    public DashboardStudent() {
        initComponents();
        
        modelMahasiswa = new DefaultTableModel();
        tableMahasiswa.setModel(modelMahasiswa);
        modelMahasiswa.addColumn("NIM");
        modelMahasiswa.addColumn("Nama Mahasiswa");
        modelMahasiswa.addColumn("Jenis Kelamin");
        modelMahasiswa.addColumn("Program Studi");
        modelMahasiswa.addColumn("Kelas");
        
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarMahasiswa = new javax.swing.JPanel();
        titleDashboardMahasiswa = new javax.swing.JLabel();
        buttonExitMahasiswa = new javax.swing.JLabel();
        buttonMinimizeMahasiswa = new javax.swing.JLabel();
        buttonLogoutMahasiswa = new javax.swing.JLabel();
        menuData = new javax.swing.JPanel();
        titleData = new javax.swing.JPanel();
        titleDataMahasiswa = new javax.swing.JLabel();
        panelData = new javax.swing.JPanel();
        txCariData = new javax.swing.JTextField();
        buttonPrint = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        menuBarMahasiswa.setBackground(new java.awt.Color(0, 0, 0));
        menuBarMahasiswa.setPreferredSize(new java.awt.Dimension(360, 40));
        menuBarMahasiswa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuBarMahasiswaMouseDragged(evt);
            }
        });

        titleDashboardMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleDashboardMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        titleDashboardMahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleDashboardMahasiswa.setText("Dashboard Mahasiswa");

        buttonExitMahasiswa.setFont(new java.awt.Font("Waree", 1, 26)); // NOI18N
        buttonExitMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        buttonExitMahasiswa.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\close.png")); // NOI18N
        buttonExitMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonExitMahasiswaMouseClicked(evt);
            }
        });

        buttonMinimizeMahasiswa.setFont(new java.awt.Font("Waree", 1, 26)); // NOI18N
        buttonMinimizeMahasiswa.setForeground(new java.awt.Color(255, 255, 255));
        buttonMinimizeMahasiswa.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\minimize.png")); // NOI18N
        buttonMinimizeMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMinimizeMahasiswaMouseClicked(evt);
            }
        });

        buttonLogoutMahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonLogoutMahasiswa.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\logout.png")); // NOI18N
        buttonLogoutMahasiswa.setToolTipText("Logout");
        buttonLogoutMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLogoutMahasiswaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuBarMahasiswaLayout = new javax.swing.GroupLayout(menuBarMahasiswa);
        menuBarMahasiswa.setLayout(menuBarMahasiswaLayout);
        menuBarMahasiswaLayout.setHorizontalGroup(
            menuBarMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarMahasiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleDashboardMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(buttonLogoutMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMinimizeMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExitMahasiswa))
        );
        menuBarMahasiswaLayout.setVerticalGroup(
            menuBarMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonExitMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buttonMinimizeMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(titleDashboardMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(buttonLogoutMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        titleData.setBackground(java.awt.Color.yellow);

        titleDataMahasiswa.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleDataMahasiswa.setForeground(java.awt.Color.darkGray);
        titleDataMahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleDataMahasiswa.setText("Data Mahasiswa");

        javax.swing.GroupLayout titleDataLayout = new javax.swing.GroupLayout(titleData);
        titleData.setLayout(titleDataLayout);
        titleDataLayout.setHorizontalGroup(
            titleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleDataMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        titleDataLayout.setVerticalGroup(
            titleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleDataMahasiswa)
                .addContainerGap())
        );

        panelData.setBackground(new java.awt.Color(255, 255, 255));
        panelData.setForeground(new java.awt.Color(255, 255, 255));

        txCariData.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txCariData.setToolTipText("Cari Data");
        txCariData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txCariDataKeyReleased(evt);
            }
        });

        buttonPrint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonPrint.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\print.png")); // NOI18N
        buttonPrint.setToolTipText("Print to .CSV");
        buttonPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPrintMouseClicked(evt);
            }
        });

        tableMahasiswa = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableMahasiswa.setFocusable(false);
        tableMahasiswa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableMahasiswa);

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPrint)
                .addGap(20, 20, 20))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txCariData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPrint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        panelDataLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonPrint, txCariData});

        javax.swing.GroupLayout menuDataLayout = new javax.swing.GroupLayout(menuData);
        menuData.setLayout(menuDataLayout);
        menuDataLayout.setHorizontalGroup(
            menuDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDataLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(menuDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        menuDataLayout.setVerticalGroup(
            menuDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDataLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(titleData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(menuBarMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(menuBarMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(menuData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExitMahasiswaMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitMahasiswaMouseClicked

    private void buttonMinimizeMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMinimizeMahasiswaMouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_buttonMinimizeMahasiswaMouseClicked

    private void buttonLogoutMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogoutMahasiswaMouseClicked
        // TODO add your handling code here:
        txCariData.setText("");
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_buttonLogoutMahasiswaMouseClicked

    private void menuBarMahasiswaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMahasiswaMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);
    }//GEN-LAST:event_menuBarMahasiswaMouseDragged

    private void txCariDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCariDataKeyReleased
        // TODO add your handling code here:
        filterTableData();
    }//GEN-LAST:event_txCariDataKeyReleased

    private void buttonPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPrintMouseClicked
        // TODO add your handling code here:
        Export export = new Export();
        try {
            export.exportMahasiswa("Portal_Data_Mahasiswa.csv");
            JOptionPane.showMessageDialog(this, "Sukses mengekspor file");
        } catch (IOException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengekspor file");
        }
    }//GEN-LAST:event_buttonPrintMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashboardStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashboardStudent().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonExitMahasiswa;
    private javax.swing.JLabel buttonLogoutMahasiswa;
    private javax.swing.JLabel buttonMinimizeMahasiswa;
    private javax.swing.JLabel buttonPrint;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menuBarMahasiswa;
    private javax.swing.JPanel menuData;
    private javax.swing.JPanel panelData;
    private javax.swing.JTable tableMahasiswa;
    private javax.swing.JLabel titleDashboardMahasiswa;
    private javax.swing.JPanel titleData;
    private javax.swing.JLabel titleDataMahasiswa;
    private javax.swing.JTextField txCariData;
    // End of variables declaration//GEN-END:variables
}
