package pdm;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    boolean isPasswordViewable = true;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JPanel();
        buttonExit = new javax.swing.JLabel();
        buttonMinimize = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        logoLogin = new javax.swing.JPanel();
        picLogo = new javax.swing.JLabel();
        titlePortalDataMahasiswa = new javax.swing.JLabel();
        headerLogin = new javax.swing.JLabel();
        iconUsername = new javax.swing.JLabel();
        iconPassword = new javax.swing.JLabel();
        txUsername = new javax.swing.JTextField();
        txPassword = new javax.swing.JPasswordField();
        viewPassword = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JLabel();
        footerLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portal Data Mahasiswa");
        setUndecorated(true);

        menuBar.setBackground(new java.awt.Color(0, 0, 0));
        menuBar.setPreferredSize(new java.awt.Dimension(360, 40));
        menuBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuBarMouseDragged(evt);
            }
        });

        buttonExit.setFont(new java.awt.Font("Waree", 1, 26)); // NOI18N
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\close.png")); // NOI18N
        buttonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonExitMouseClicked(evt);
            }
        });

        buttonMinimize.setFont(new java.awt.Font("Waree", 1, 26)); // NOI18N
        buttonMinimize.setForeground(new java.awt.Color(255, 255, 255));
        buttonMinimize.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\minimize.png")); // NOI18N
        buttonMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExit))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(buttonMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginPanel.setBackground(new java.awt.Color(245, 245, 245));

        logoLogin.setBackground(new java.awt.Color(245, 245, 245));

        picLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        picLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\loginpic.png")); // NOI18N
        picLogo.setToolTipText("Portal Data Mahasiswa");

        javax.swing.GroupLayout logoLoginLayout = new javax.swing.GroupLayout(logoLogin);
        logoLogin.setLayout(logoLoginLayout);
        logoLoginLayout.setHorizontalGroup(
            logoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(picLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoLoginLayout.setVerticalGroup(
            logoLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLoginLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(picLogo)
                .addGap(0, 0, 0))
        );

        titlePortalDataMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titlePortalDataMahasiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePortalDataMahasiswa.setText("Portal Data Mahasiswa");

        headerLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        headerLogin.setForeground(new java.awt.Color(255, 0, 0));
        headerLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLogin.setText("Silakan Login Terlebih Dahulu");

        iconUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iconUsername.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\user.png")); // NOI18N
        iconUsername.setToolTipText("Username");

        iconPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iconPassword.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\password.png")); // NOI18N
        iconPassword.setToolTipText("Password");

        txUsername.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txUsername.setToolTipText("Username");

        txPassword.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txPassword.setToolTipText("Password");

        viewPassword.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\show.png")); // NOI18N
        viewPassword.setToolTipText("Show Password");
        viewPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPasswordMouseClicked(evt);
            }
        });

        buttonLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRIDAY\\Documents\\NetBeansProjects\\PDM\\src\\img\\login.png")); // NOI18N
        buttonLogin.setToolTipText("Log In");
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginMouseClicked(evt);
            }
        });

        footerLogin.setForeground(new java.awt.Color(0, 0, 127));
        footerLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerLogin.setText("Silakan hubungi Admin untuk registrasi akun baru dan lupa password");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePortalDataMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconUsername)
                            .addComponent(iconPassword))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txUsername)
                            .addComponent(txPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(viewPassword))
                    .addComponent(buttonLogin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(logoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(titlePortalDataMahasiswa)
                .addGap(25, 25, 25)
                .addComponent(headerLogin)
                .addGap(25, 25, 25)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconUsername)
                    .addComponent(txUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconPassword)
                    .addComponent(txPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPassword))
                .addGap(25, 25, 25)
                .addComponent(buttonLogin)
                .addGap(25, 25, 25)
                .addComponent(footerLogin)
                .addGap(50, 50, 50))
        );

        loginPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {iconUsername, txUsername});

        loginPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {iconPassword, txPassword, viewPassword});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addComponent(loginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitMouseClicked

    private void buttonMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_buttonMinimizeMouseClicked

    private void menuBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);
    }//GEN-LAST:event_menuBarMouseDragged

    private void viewPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPasswordMouseClicked
        // TODO add your handling code here:

        // Menampilkan dan menyembunyikan Password yang diketik
        if (isPasswordViewable) {
            txPassword.setEchoChar((char) 0);
            isPasswordViewable = !isPasswordViewable;
            viewPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hide.png")));
            viewPassword.setToolTipText("Hide Password");
        } else {
            txPassword.setEchoChar('*');
            isPasswordViewable = !isPasswordViewable;
            viewPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/show.png")));
            viewPassword.setToolTipText("Show Password");
        }
    }//GEN-LAST:event_viewPasswordMouseClicked

    private void buttonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseClicked
        // TODO add your handling code here:
        String username = txUsername.getText();
        String password = String.valueOf(txPassword.getPassword());

        String ErrorMessage = "";
        if (username.equals("") && password.equals("")) {
            ErrorMessage += "Username dan Password tidak boleh kosong.\n";
        } else if (username.equals("")) {
            ErrorMessage += "Username tidak boleh kosong.\n";
        } else if (password.equals("")) {
            ErrorMessage += "Password tidak boleh kosong.";
        }

        if (ErrorMessage.isEmpty()) {
            PreparedStatement p;
            ResultSet r;
            String sql = "SELECT * FROM akun WHERE username = ?";
            try {
                p = Config.getConnection().prepareStatement(sql);
                p.setString(1, username);
                r = p.executeQuery();
                if (r.next()) {
                    String dbpassword = r.getString("katasandi");
                    String dbrole = r.getString("role");

                    if (password.equals(dbpassword)) {
                        if (dbrole.equals("Admin")) {
                            new DashboardAdmin().setVisible(true);
                            this.setVisible(false);
                        } else if (dbrole.equals("Student")) {
                            new DashboardStudent().setVisible(true);
                            this.setVisible(false);
                        }
                    } else {
                        JOptionPane.showMessageDialog(new JFrame(), "Password salah", "Gagal Login", 2);
                    }
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Username tidak ditemukan", "Gagal Login", 2);
                }
            } catch (HeadlessException | SQLException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, ErrorMessage, "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonExit;
    private javax.swing.JLabel buttonLogin;
    private javax.swing.JLabel buttonMinimize;
    private javax.swing.JLabel footerLogin;
    private javax.swing.JLabel headerLogin;
    private javax.swing.JLabel iconPassword;
    private javax.swing.JLabel iconUsername;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel logoLogin;
    private javax.swing.JPanel menuBar;
    private javax.swing.JLabel picLogo;
    private javax.swing.JLabel titlePortalDataMahasiswa;
    private javax.swing.JPasswordField txPassword;
    private javax.swing.JTextField txUsername;
    private javax.swing.JLabel viewPassword;
    // End of variables declaration//GEN-END:variables
}
